#ifndef WAYPOINTTYPE_H
#define WAYPOINTTYPE_H

#include <QObject>

namespace WP{
    Q_NAMESPACE
    enum WayPointType : int {
        UNDEFINED_POINT,
        TAKEOFF_POINT,
        FINISH_POINT,
        TURN_POINT,
        EVENT_POINT,
        CLIMB_POINT,
        DESCENT_POINT,
        CRUISE_POINT,
        MARKER_POINT,
        IMG_POINT,
        DEM_POINT,

        WAYPOINT_BASE,
        ACCEL_START,
        TURN_START,
        TURN_FINISH,
        CLIMB_START,
        CLIMB_FINISH,
        DESCENT_START,
        DESCENT_FINISH,
        DEM_START,
        DEM_FINISH,
        IMG_START,
        IMG_FINISH,
        CLIMB_CRUISE_START,
        CLIMB_CRUISE_FINISH,
        CRUISE_CLIMB_START,
        CRUISE_CLIMB_FINISH,
        CLIMB_CLIMB_RAISE_START,
        CLIMB_CLIMB_RAISE_FINISH,
        CLIMB_CLIMB_LOWER_START,
        CLIMB_CLIMB_LOWER_FINISH,
        CLIMB_DESCENT_START,
        CLIMB_DESCENT_FINISH,
        DESCENT_CRUISE_START,
        DESCENT_CRUISE_FINISH,
        CRUISE_DESCENT_START,
        CRUISE_DESCENT_FINISH,
        DESCENT_DESCENT_LOWER_START,
        DESCENT_DESCENT_LOWER_FINISH,
        DESCENT_DESCENT_RAISE_START,
        DESCENT_DESCENT_RAISE_FINISH,
        DESCENT_CLIMB_START,
        DESCENT_CLIMB_FINISH,
        SWITCH_ORTHODROMY,
    };
    Q_ENUM_NS(WayPointType);
};
#endif // WAYPOINTTYPE_H
